# Generated by Django 5.2 on 2025-08-26 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('closed', 'Fermé'), ('spam', 'Spam')], default='new', max_length=20, verbose_name='Statut')),
                ('source', models.CharField(choices=[('website', 'Site web'), ('whatsapp', 'WhatsApp'), ('phone', 'Téléphone'), ('email', 'Email'), ('form', 'Formulaire de contact')], default='form', max_length=20, verbose_name='Source')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Répondu le')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='agencies.agency', verbose_name='Agence')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cars.listing', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Demande de renseignements',
                'verbose_name_plural': 'Demandes de renseignements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='Réponse')),
                ('sent_by', models.CharField(max_length=100, verbose_name='Envoyé par')),
                ('sent_via', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Téléphone'), ('sms', 'SMS')], max_length=20, verbose_name='Envoyé via')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiries.inquiry', verbose_name='Demande')),
            ],
            options={
                'verbose_name': 'Réponse à la demande',
                'verbose_name_plural': 'Réponses aux demandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
