# Generated by Django 5.2 on 2025-08-26 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Année')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilométrage')),
                ('fuel', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride'), ('lpg', 'GPL')], max_length=20, verbose_name='Carburant')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique'), ('semi_auto', 'Semi-automatique')], max_length=20, verbose_name='Boîte de vitesse')),
                ('body', models.CharField(choices=[('sedan', 'Berline'), ('suv', 'SUV'), ('hatchback', 'Citadine'), ('wagon', 'Break'), ('coupe', 'Coupé'), ('convertible', 'Cabriolet'), ('van', 'Fourgon'), ('pickup', 'Pick-up')], max_length=20, verbose_name='Carrosserie')),
                ('engine_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Cylindrée (L)')),
                ('power', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance (ch)')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Options')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='agencies.agency', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/', verbose_name='Image')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Image de couverture')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre de tri')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texte alternatif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Image de voiture',
                'verbose_name_plural': 'Images de voiture',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location')], max_length=10, verbose_name="Type d'annonce")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('paused', 'En pause'), ('sold', 'Vendu'), ('rented', 'Loué')], default='draft', max_length=20, verbose_name='Statut')),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente')),
                ('price_rent_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix location/jour')),
                ('price_rent_weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix location/semaine')),
                ('price_rent_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix location/mois')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
                'unique_together': {('car', 'type')},
            },
        ),
        migrations.CreateModel(
            name='RentalTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarif journalier')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarif hebdomadaire')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarif mensuel')),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Caution requise')),
                ('min_rental_days', models.PositiveIntegerField(default=1, verbose_name='Jours minimum de location')),
                ('max_rental_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jours maximum de location')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='Lieu de retrait')),
                ('return_location', models.CharField(blank=True, max_length=200, verbose_name='Lieu de retour')),
                ('fuel_policy', models.CharField(default='full_to_full', max_length=50, verbose_name='Politique carburant')),
                ('mileage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite kilométrage/jour')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_terms', to='cars.listing', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Conditions de location',
                'verbose_name_plural': 'Conditions de location',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name="Raison de l'indisponibilité")),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='cars.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['date'],
                'unique_together': {('car', 'date')},
            },
        ),
    ]
