# Generated by Django 5.2 on 2025-08-26 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rent', 'Location'), ('test_drive', 'Essai')], max_length=20, verbose_name='Type de réservation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('expired', 'Expiré'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('test_drive_date', models.DateTimeField(blank=True, null=True, verbose_name="Date et heure d'essai")),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant de la caution')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='agencies.agency', verbose_name='Agence')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.listing', verbose_name='Annonce')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Type de notification')),
                ('sent_to', models.CharField(max_length=200, verbose_name='Envoyé à')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Notification de réservation',
                'verbose_name_plural': 'Notifications de réservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
